import { FormEvent, useEffect, useMemo, useState } from 'react';
import { api } from '../api';
import type { FileItem, ImpactResult, Investigation, PlanResult, Workspace } from '../types';

type View = 'overview' | 'architecture' | 'investigate' | 'impact' | 'plan';
const findFile = (workspace: Workspace, path: string) => workspace.files.find(file => file.path === path);

export function Overview({ workspace, open, openSource }: { workspace: Workspace; open: (view: View) => void; openSource: (file: FileItem) => void }) {
  const languages = Object.entries(workspace.languages).sort((a, b) => b[1].lines - a[1].lines);
  const dependents = new Map<string, number>();
  workspace.edges.filter(edge => edge.kind === 'relative').forEach(edge => dependents.set(edge.target, (dependents.get(edge.target) || 0) + 1));
  const hotspots = [...workspace.files].sort((a, b) => (dependents.get(b.path) || 0) - (dependents.get(a.path) || 0)).slice(0, 5);
  const largest = [...workspace.files].sort((a, b) => b.lines - a.lines).slice(0, 5);
  const internalEdges = workspace.edges.filter(edge => edge.kind === 'relative').length;
  return <div className="page-content"><div className="page-heading"><div><p className="eyebrow">YOUR REPOSITORY BRIEFING</p><h1>The codebase at a glance.</h1><p>Start with the system shape, then follow the areas that deserve a closer look.</p></div><button className="outline-action" onClick={() => open('architecture')}>Explore architecture ↗</button></div><div className="summary-grid"><div><span>SOURCE FILES</span><strong>{workspace.metrics.files.toLocaleString()}</strong><small>Across {languages.length} languages</small></div><div><span>INTERNAL LINKS</span><strong>{internalEdges.toLocaleString()}</strong><small>Imports between scanned files</small></div><div><span>LINES SCANNED</span><strong>{workspace.metrics.lines.toLocaleString()}</strong><small>Indexed for exploration</small></div></div><div className="dashboard-grid"><section className="surface-card"><div className="card-heading"><div><small>COMPOSITION</small><h2>Languages</h2></div><span>{languages.length} detected</span></div><div className="language-bars">{languages.slice(0, 8).map(([name, value]) => <div className="language-item" key={name}><span>{name}</span><div className="bar-track"><i style={{ width: `${Math.max(3, (value.lines / Math.max(1, workspace.metrics.lines)) * 100)}%` }}/></div><b>{value.files} files</b></div>)}</div></section><section className="surface-card"><div className="card-heading"><div><small>HIGH CONNECTIVITY</small><h2>Dependency hotspots</h2></div><button onClick={() => open('impact')}>Assess risk →</button></div><p className="card-intro">Files imported by the most other scanned modules.</p><div className="rank-list">{hotspots.map((file, index) => <button key={file.path} onClick={() => openSource(file)}><b>{String(index + 1).padStart(2, '0')}</b><span><strong>{file.path.split('/').pop()}</strong><small>{file.path}</small></span><em>{dependents.get(file.path) || 0} dependents</em></button>)}</div></section><section className="surface-card"><div className="card-heading"><div><small>SOURCE WEIGHT</small><h2>Largest modules</h2></div></div><div className="rank-list">{largest.map(file => <button key={file.path} onClick={() => openSource(file)}><span><strong>{file.path.split('/').pop()}</strong><small>{file.path}</small></span><em>{file.lines.toLocaleString()} lines</em></button>)}</div></section><section className="surface-card next-step-card"><small>WHERE TO NEXT</small><h2>Follow a useful path.</h2><p>Map a module, ask a grounded question, or inspect the impact of changing a file.</p><div><button onClick={() => open('architecture')}>Map relationships <span>→</span></button><button onClick={() => open('investigate')}>Ask the codebase <span>→</span></button><button onClick={() => open('plan')}>Plan a change <span>→</span></button></div></section></div></div>;
}

const prompts = ['Where does request handling begin?', 'Which files define the main API?', 'How are components organized?'];
export function InvestigationView({ workspace, onSource }: { workspace: Workspace; onSource: (file: FileItem, line?: number) => void }) {
  const [question, setQuestion] = useState(''); const [submitted, setSubmitted] = useState(''); const [result, setResult] = useState<Investigation>(); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  async function ask(value = question) { if (!value.trim()) return; setQuestion(value); setSubmitted(value); setBusy(true); setError(''); try { setResult(await api.investigate(workspace.workspaceId, value)); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Investigation failed.'); } finally { setBusy(false); } }
  return <div className="page-content"><div className="page-heading"><div><p className="eyebrow">SOURCE GROUNDED INVESTIGATION</p><h1>Ask a better question.</h1><p>Answers start with matching source. Open any cited file to check the evidence yourself.</p></div></div><div className="investigation-layout"><div className="conversation"><div className="conversation-intro"><span className="conversation-icon">⌕</span><h2>What would you like to understand?</h2><p>Ask about a feature, route, symbol, or architectural decision in {workspace.repository.name}.</p><div className="suggestions">{prompts.map(prompt => <button key={prompt} onClick={() => void ask(prompt)}>{prompt} <span>↗</span></button>)}</div></div>{result && <div className="answer-block"><div className="question-bubble">{submitted}</div><article><div className="answer-label"><span className="live-dot"/> {result.mode === 'gemini-grounded' ? 'GEMINI ANSWER' : 'SOURCE SEARCH RESULT'} <small>· {result.evidence.length} sources</small></div><p>{result.answer}</p></article></div>}{error && <p className="error-banner" role="alert">{error}</p>}</div><aside className="evidence-panel"><div className="card-heading"><div><small>VERIFIABLE CONTEXT</small><h2>Source evidence</h2></div></div>{result?.evidence.length ? result.evidence.map((item, index) => { const file = findFile(workspace, item.filePath); return <button key={item.filePath} onClick={() => file && onSource(file, item.lineStart)}><small>REFERENCE {String(index + 1).padStart(2, '0')} · LINE {item.lineStart}</small><strong>{item.filePath}</strong><code>{item.snippet}</code></button>; }) : <div className="quiet-empty">Matching files and snippets appear here after you ask a question.</div>}</aside></div><form className="composer" onSubmit={(event: FormEvent) => { event.preventDefault(); void ask(); }}><input aria-label="Question about the repository" value={question} onChange={event => setQuestion(event.target.value)} placeholder="Ask about a route, feature, symbol…"/><button disabled={!question.trim() || busy}>{busy ? 'Searching…' : 'Ask repository ↗'}</button></form></div>;
}

export function ImpactView({ workspace, initialFile, onSource }: { workspace: Workspace; initialFile?: FileItem; onSource: (file: FileItem) => void }) {
  const [path, setPath] = useState(initialFile?.path || ''); const [result, setResult] = useState<ImpactResult>(); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [filter, setFilter] = useState('');
  useEffect(() => { if (initialFile) setPath(initialFile.path); }, [initialFile]);
  useEffect(() => { if (!initialFile) return; let live = true; setBusy(true); api.impact(workspace.workspaceId, initialFile.path).then(value => { if (live) setResult(value); }).catch(caught => { if (live) setError(caught instanceof Error ? caught.message : 'Impact analysis failed.'); }).finally(() => { if (live) setBusy(false); }); return () => { live = false; }; }, [initialFile, workspace.workspaceId]);
  const selectedPath = path;
  const affected = result?.affected.filter(file => file.path.toLowerCase().includes(filter.toLowerCase())) || [];
  async function assess(candidate = selectedPath) { if (!candidate) return; setPath(candidate); setBusy(true); setError(''); try { setResult(await api.impact(workspace.workspaceId, candidate)); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Impact analysis failed.'); } finally { setBusy(false); } }
  return <div className="page-content"><div className="page-heading"><div><p className="eyebrow">CHANGE IMPACT</p><h1>Know what a change touches.</h1><p>Choose a source file and trace the modules that import it, directly or through other files.</p></div></div><div className="impact-picker surface-card"><div className="card-heading"><div><small>STEP 01</small><h2>Select a module</h2></div></div><div className="picker-row"><select aria-label="File to assess" value={selectedPath} onChange={event => setPath(event.target.value)}><option value="">Choose a source file…</option>{workspace.files.map(file => <option value={file.path} key={file.path}>{file.path}</option>)}</select><button onClick={() => void assess()} disabled={!selectedPath || busy}>{busy ? 'Tracing…' : 'Assess impact ↗'}</button></div></div>{error && <p className="error-banner" role="alert">{error}</p>}{result ? <div className="impact-results"><div className="risk-summary"><div><small>IMPACT ASSESSMENT</small><h2>{result.affected.length} affected {result.affected.length === 1 ? 'module' : 'modules'}</h2><p>Changing <b>{result.targetPath}</b> may affect the files listed below.</p></div><span className={`risk-tag ${result.risk}`}>{result.risk.toUpperCase()} RISK</span></div><div className="surface-card"><div className="card-heading"><div><small>DEPENDENCY PATHS</small><h2>Downstream files</h2></div><input aria-label="Filter affected files" placeholder="Filter files…" value={filter} onChange={event => setFilter(event.target.value)}/></div>{affected.length ? <div className="affected-table"><div className="table-head"><span>FILE</span><span>RELATION</span><span></span></div>{affected.map(item => <button key={item.path} onClick={() => { const file = findFile(workspace, item.path); if (file) onSource(file); }}><strong>{item.path}</strong><span>{item.depth === 1 ? 'Direct dependent' : `${item.depth} steps away`}</span><em>View source ↗</em></button>)}</div> : <div className="quiet-empty">No files match this filter. A file with zero dependents is a leaf in the current import map.</div>}</div></div> : <div className="instruction-card"><span>↗</span><div><strong>Trace before you change.</strong><p>Select a module above to see who depends on it and how far the effects can travel.</p></div></div>}</div>;
}

export function PlanView({ workspace, onSource }: { workspace: Workspace; onSource: (file: FileItem) => void }) {
  const [request, setRequest] = useState(''); const [result, setResult] = useState<PlanResult>(); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  async function generate(event: FormEvent) { event.preventDefault(); if (!request.trim()) return; setBusy(true); setError(''); try { setResult(await api.plan(workspace.workspaceId, request)); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Could not create a plan.'); } finally { setBusy(false); } }
  const targetFiles = useMemo(() => result?.targetFiles || [], [result]);
  return <div className="page-content"><div className="page-heading"><div><p className="eyebrow">CHANGE PLANNING</p><h1>Turn intent into a path.</h1><p>Describe the change. Aqua Lens suggests a starting point, affected files, and a verification sequence.</p></div></div><form className="plan-composer surface-card" onSubmit={generate}><label htmlFor="change-request">WHAT DO YOU WANT TO CHANGE?</label><textarea id="change-request" value={request} onChange={event => setRequest(event.target.value)} placeholder="For example: add validation to the main request handler…" rows={4}/><div><small>Plans are proposals. Review source and tests before editing.</small><button disabled={!request.trim() || busy}>{busy ? 'Creating plan…' : 'Create change plan ↗'}</button></div></form>{error && <p className="error-banner" role="alert">{error}</p>}{result ? <div className="plan-layout"><section className="surface-card"><div className="card-heading"><div><small>PROPOSED APPROACH</small><h2>{result.title}</h2></div></div><p className="card-intro">{result.summary}</p><div className="timeline">{result.steps.map(step => <div key={step.order}><span>{String(step.order).padStart(2, '0')}</span><div><strong>{step.title}</strong><p>{step.description}</p></div></div>)}</div></section><aside className="surface-card"><div className="card-heading"><div><small>CHECK THE BASIS</small><h2>Relevant files</h2></div></div>{targetFiles.length ? targetFiles.map(path => { const file = findFile(workspace, path); return <button className="file-link" key={path} onClick={() => file && onSource(file)}>{path}<span>↗</span></button>; }) : <p className="quiet-empty">No strong target file found. Add a feature or symbol name to your request.</p>}<div className="verification"><small>BEFORE MERGING</small><p>Review the cited source, test changed behavior, and inspect downstream modules.</p></div></aside></div> : <div className="instruction-card"><span>▤</span><div><strong>Start with a specific goal.</strong><p>Include a feature, route, file, or symbol so the plan can point to relevant source.</p></div></div>}</div>;
}
